from __future__ import annotations

import os
from pathlib import Path

from file_utils import path_contains_any
from project_context import RuntimeConfig


def generate_dynamic_file_list(runtime: RuntimeConfig, tb_path: Path | None = None) -> Path:
    runtime.sim_dir.mkdir(parents=True, exist_ok=True)

    sources = discover_hdl_files(runtime, tb_path)

    with runtime.filelist_path.open("w", encoding="utf-8") as filelist:
        filelist.write("// Auto-generated by auto_verilator\n")
        filelist.write(f"// Config: {runtime.conf.path}\n\n")
        filelist.write("// HDL sources\n")
        for source in sources:
            try:
                rel_path = os.path.relpath(source, runtime.sim_dir)
            except ValueError:
                rel_path = str(source)
            filelist.write(rel_path.replace("\\", "/") + "\n")

        filelist.write("\n// Verilator flags\n")
        for flag in runtime.filelist_flags:
            filelist.write(flag + "\n")

    return runtime.filelist_path


def discover_hdl_files(runtime: RuntimeConfig, tb_path: Path | None = None) -> list[Path]:
    if not runtime.rtl_dir.exists():
        raise FileNotFoundError(f"RTL directory not found: {runtime.rtl_dir}")

    allowed_exts = {f".{extension.lower().lstrip('.')}" for extension in runtime.hdl_extensions}
    skip_tb = tb_path.resolve() if tb_path else None
    discovered: list[Path] = []

    for root, dirs, files in os.walk(runtime.rtl_dir):
        dirs.sort()
        files.sort()
        for filename in files:
            path = (Path(root) / filename).resolve()

            if path.suffix.lower() not in allowed_exts:
                continue

            if skip_tb and path == skip_tb:
                continue

            normalized_lower = str(path).lower()
            if "vivado" in normalized_lower:
                continue

            if path_contains_any(str(path), list(runtime.exclude_folders)):
                continue

            if _has_skip_flag(path):
                continue

            discovered.append(path)

    return sorted(discovered, key=lambda path: _source_sort_key(path, runtime.folder_order))


def _has_skip_flag(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8") as source_file:
            head = source_file.read(400)
        return "VERILATOR_SKIP" in head
    except OSError:
        return False


def _source_sort_key(path: Path, folder_order: tuple[str, ...]) -> tuple[int, str]:
    path_parts = {part.lower() for part in path.parts}
    folder_index = len(folder_order)
    for idx, folder in enumerate(folder_order):
        if folder.lower() in path_parts:
            folder_index = idx
            break
    return folder_index, str(path).lower()
